#!/usr/bin/env bash
# sync-mirrors.sh
# Propagate SSOT files (skills + rules + data) to every IDE mirror location.
# Every .cursor/, .claude/, .windsurf/, .clinerules/, .github/, .vscode/,
# AGENTS.md, GEMINI.md, CLAUDE.md file in this repo is generated by this script.
#
# Idempotent. Safe to run repeatedly. CI invokes it via scripts/verify-repo.sh
# and fails on byte-for-byte drift.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SKILLS=(asset-enhancer logo app-icon favicon og-image illustration transparent-bg vectorize)
RULE_BODY="rules/asset-enhancer-activate.md"

# ============================================================================
# 1. Claude Code
# ============================================================================
mkdir -p .claude-plugin .claude/skills
cat > .claude-plugin/plugin.json <<EOF
{
  "name": "prompt-to-asset",
  "version": "0.1.0",
  "description": "Reliably generate production-grade software assets (logos, app icons, favicons, OG images, illustrations, vectors, transparent marks) from simple briefs.",
  "author": { "name": "prompt-to-asset contributors" },
  "license": "MIT",
  "skills": ["./skills"],
  "mcp": {
    "servers": {
      "prompt-to-asset": {
        "command": "node",
        "args": ["./packages/mcp-server/dist/index.js"]
      }
    }
  }
}
EOF

for sk in "${SKILLS[@]}"; do
  mkdir -p ".claude/skills/$sk"
  cp "skills/$sk/SKILL.md" ".claude/skills/$sk/SKILL.md"
done
# Also copy under plugin-bundle layout
mkdir -p plugins/prompt-to-asset/skills
for sk in "${SKILLS[@]}"; do
  mkdir -p "plugins/prompt-to-asset/skills/$sk"
  cp "skills/$sk/SKILL.md" "plugins/prompt-to-asset/skills/$sk/SKILL.md"
done
cp .claude-plugin/plugin.json plugins/prompt-to-asset/.claude-plugin/plugin.json 2>/dev/null || {
  mkdir -p plugins/prompt-to-asset/.claude-plugin
  cp .claude-plugin/plugin.json plugins/prompt-to-asset/.claude-plugin/plugin.json
}

# CLAUDE.md — the top-level memory for Claude Code
{
  printf '# prompt-to-asset (Claude Code memory)\n\n'
  printf 'This repo registers a `prompt-to-asset` MCP server and a set of skills for generating production-grade software assets. When the user asks for a logo, app icon, favicon, OG image, illustration, splash screen, icon pack, transparent mark, or hero image, follow the rule below and prefer the `asset_*` MCP tool surface.\n\n'
  cat "$RULE_BODY"
} > CLAUDE.md

# ============================================================================
# 2. Cursor
# ============================================================================
mkdir -p .cursor/rules .cursor/skills

# Rule — frontmattered .mdc
{
  printf '%s\n' '---'
  printf 'description: Asset generation — route, rewrite, generate, validate. Never send transparency requests to Imagen/Gemini.\n'
  printf 'alwaysApply: true\n'
  printf '%s\n\n' '---'
  cat "$RULE_BODY"
} > .cursor/rules/prompt-to-asset.mdc

# Skills (Cursor reads SKILL.md identically to Claude Code)
for sk in "${SKILLS[@]}"; do
  mkdir -p ".cursor/skills/$sk"
  cp "skills/$sk/SKILL.md" ".cursor/skills/$sk/SKILL.md"
done

# MCP registration
cat > .cursor/mcp.json <<EOF
{
  "mcpServers": {
    "prompt-to-asset": {
      "command": "node",
      "args": ["\${workspaceFolder}/packages/mcp-server/dist/index.js"]
    }
  }
}
EOF

# ============================================================================
# 3. Windsurf
# ============================================================================
mkdir -p .windsurf/rules .windsurf/skills
{
  printf '%s\n' '---'
  printf 'description: Asset generation — route, rewrite, generate, validate.\n'
  printf 'activation: always_on\n'
  printf '%s\n\n' '---'
  cat "$RULE_BODY"
} > .windsurf/rules/prompt-to-asset.md
for sk in "${SKILLS[@]}"; do
  mkdir -p ".windsurf/skills/$sk"
  cp "skills/$sk/SKILL.md" ".windsurf/skills/$sk/SKILL.md"
done

# ============================================================================
# 4. Cline
# ============================================================================
mkdir -p .clinerules
{
  printf '# prompt-to-asset (Cline rule)\n\n'
  cat "$RULE_BODY"
} > .clinerules/01-prompt-to-asset.md

# ============================================================================
# 5. Codex CLI (OpenAI)
# ============================================================================
{
  printf '# AGENTS.md — prompt-to-asset\n\n'
  printf 'This repo exposes a `prompt-to-asset` MCP server (stdio). When generating software assets, follow the rule below and prefer the `asset_*` MCP tool surface over ad-hoc image generation.\n\n'
  cat "$RULE_BODY"
} > AGENTS.md

mkdir -p .codex
cat > .codex/config.toml <<EOF
# Codex CLI — prompt-to-asset MCP registration
[mcp_servers.prompt-to-asset]
command = "node"
args = ["./packages/mcp-server/dist/index.js"]
EOF

mkdir -p plugins/prompt-to-asset/.codex-plugin
cat > plugins/prompt-to-asset/.codex-plugin/plugin.json <<EOF
{
  "name": "prompt-to-asset",
  "version": "0.1.0",
  "entry": "packages/mcp-server/dist/index.js"
}
EOF

# ============================================================================
# 6. Gemini CLI
# ============================================================================
cat > gemini-extension.json <<EOF
{
  "name": "prompt-to-asset",
  "version": "0.1.0",
  "contextFileName": ["GEMINI.md", "skills/**/SKILL.md"],
  "mcpServers": {
    "prompt-to-asset": {
      "command": "node",
      "args": ["packages/mcp-server/dist/index.js"]
    }
  }
}
EOF

{
  printf '# GEMINI.md — prompt-to-asset\n\n'
  printf 'This project registers a `prompt-to-asset` MCP server. When the user asks for a software asset, use the `asset_*` tool surface and follow this rule:\n\n'
  cat "$RULE_BODY"
  printf '\n\n## Reminder for Gemini specifically\n\n'
  printf 'Gemini Flash Image and Imagen 3/4 render a checkerboard as RGB pixels when asked for a transparent background. Do not attempt transparency via prompt; route transparency requests to `asset_generate_logo` / `asset_generate_app_icon` / `asset_remove_background` — those tools route away from Gemini for transparency-required outputs.\n'
} > GEMINI.md

# ============================================================================
# 7. GitHub Copilot
# ============================================================================
mkdir -p .github
{
  printf '# Copilot instructions — prompt-to-asset\n\n'
  printf 'When generating software assets (logos, icons, favicons, OG cards, illustrations) in this repository, always follow this rule and prefer the `asset_*` MCP tool surface over ad-hoc image generation:\n\n'
  cat "$RULE_BODY"
} > .github/copilot-instructions.md

# Copilot Skillset — 5-skill cap workaround (one god-skill branching by asset_type)
cat > .github/copilot-skillset.json <<EOF
{
  "name": "prompt-to-asset",
  "skills": [
    {
      "name": "asset_generate",
      "description": "Generate a production-grade software asset (logo, app icon, favicon, OG image, illustration, vector). Classifies and routes internally. Prefer this over ad-hoc image generation.",
      "inputs": {
        "asset_type": { "type": "string", "enum": ["logo", "app_icon", "favicon", "og_image", "illustration", "icon_pack", "sticker", "transparent_mark", "hero"] },
        "brief": { "type": "string" },
        "brand_bundle": { "type": "object" }
      }
    }
  ]
}
EOF

# ============================================================================
# 8. VS Code MCP
# ============================================================================
mkdir -p .vscode
cat > .vscode/mcp.json <<EOF
{
  "servers": {
    "prompt-to-asset": {
      "type": "stdio",
      "command": "node",
      "args": ["\${workspaceFolder}/packages/mcp-server/dist/index.js"]
    }
  }
}
EOF

echo "sync-mirrors: done."
